package dev.understudy.install

import android.content.Context
import android.content.pm.PackageManager
import dev.understudy.packaging.ProxyApkFactory
import dev.understudy.packaging.sign.SigningIdentity
import java.io.File
import java.io.IOException
import java.security.MessageDigest

/**
 * Produces installable proxy APKs on demand.
 *
 * Two responsibilities that are easy to conflate:
 *  - **identity**: load-or-create the signing key, which must stay stable across runs or a
 *    previously installed proxy can no longer be updated in place;
 *  - **materialisation**: read the template asset, re-target it, and write the result somewhere
 *    `PackageInstaller` can stream from.
 *
 * The template lives in assets rather than being generated because it is the output of the
 * `:proxy` Gradle module — real compiled Kotlin, type-checked and unit-tested by the normal
 * toolchain, not something assembled by hand at runtime.
 */
class ApkGenerator(private val context: Context) {

    /** Cached so repeated generations do not re-read the asset or re-parse the certificate. */
    private var cachedIdentity: SigningIdentity? = null
    private var cachedTemplate: ByteArray? = null

    /** The signing identity in use. Created on first access and persisted thereafter. */
    @Synchronized
    fun identity(): SigningIdentity {
        cachedIdentity?.let { return it }
        val created = SigningIdentity.loadOrCreate(File(context.filesDir, KEY_DIR))
        cachedIdentity = created
        return created
    }

    /** SHA-256 fingerprint of the signing certificate, for display and for diagnostics. */
    fun fingerprint(): String = identity().fingerprintHex

    /**
     * Generates a proxy APK impersonating [targetPackage] and writes it to [outputDir].
     *
     * @return the written file plus metadata worth showing the user
     */
    fun generate(targetPackage: String, outputDir: File = defaultOutputDir()): GeneratedApk {
        val template = template()
        val apk = ProxyApkFactory(identity()).generate(
            template,
            targetPackage,
            generatorCertificateSha256Hex = ownCertificateSha256Hex(),
        )

        outputDir.mkdirs()
        val file = File(outputDir, fileNameFor(targetPackage))
        try {
            file.writeBytes(apk.bytes)
        } catch (e: IOException) {
            throw IOException("could not write ${file.name}: ${e.message}", e)
        }

        return GeneratedApk(
            file = file,
            packageName = apk.packageName,
            authority = apk.authority,
            sizeBytes = apk.sizeBytes,
            sha256Hex = apk.sha256Hex,
            manifestReplacements = apk.manifestReplacements,
        )
    }

    /** Removes every previously generated APK. Safe to call at any time. */
    fun clearGenerated() {
        defaultOutputDir().listFiles()?.forEach { it.delete() }
    }

    /**
     * SHA-256 of THIS app's signing certificate, baked into every proxy we generate.
     *
     * The proxy uses it to authenticate its caller. A `signature`-level permission cannot do
     * that job in production: it requires caller and provider to share a certificate, but the
     * proxy is signed with a per-install key generated on the device while this app is signed at
     * build time, so they can never match. What the proxy actually needs to know is "was I
     * generated by this particular Understudy install", and this digest is the only thing that
     * can answer it.
     *
     * Returns null if the platform will not tell us our own signer — in which case the proxy is
     * generated without the asset and falls back to permission-only enforcement, rather than
     * being generated with a digest that would lock out its own creator.
     */
    @Suppress("DEPRECATION")
    fun ownCertificateSha256Hex(): String? = runCatching {
        val pm = context.packageManager
        val pkg = context.packageName
        // `SigningInfo` (and therefore GET_SIGNING_CERTIFICATES) is API 28, and minSdk is 26, so
        // both routes are needed. Below 28 the deprecated `signatures` array is the only source;
        // it is still correct for a non-rotated key, which is the overwhelmingly common case and
        // the only case this app can be in on those versions.
        val cert = if (android.os.Build.VERSION.SDK_INT >= 28) {
            val signing = pm.getPackageInfo(pkg, PackageManager.GET_SIGNING_CERTIFICATES).signingInfo
                ?: return@runCatching null
            // A package with rotated keys reports both; the current signer is what a fresh
            // install of this build will present, so that is the one to pin.
            (if (signing.hasMultipleSigners()) signing.apkContentsSigners
                else signing.signingCertificateHistory)?.firstOrNull()
        } else {
            @Suppress("PackageManagerGetSignatures")
            pm.getPackageInfo(pkg, PackageManager.GET_SIGNATURES).signatures?.firstOrNull()
        } ?: return@runCatching null

        MessageDigest.getInstance("SHA-256").digest(cert.toByteArray())
            .joinToString("") { byte -> "%02x".format(byte) }
    }.getOrNull()

    private fun template(): ByteArray {
        cachedTemplate?.let { return it }
        val bytes = context.assets.open(TEMPLATE_ASSET).use { it.readBytes() }
        require(bytes.size > MIN_TEMPLATE_SIZE) {
            "$TEMPLATE_ASSET is ${bytes.size} bytes — the :proxy module did not build into it. " +
                "Run ./gradlew :app:syncProxyTemplate."
        }
        cachedTemplate = bytes
        return bytes
    }

    private fun defaultOutputDir(): File = File(context.cacheDir, GENERATED_DIR)

    companion object {
        const val TEMPLATE_ASSET = "proxy-template.apk"
        private const val KEY_DIR = "signing"
        private const val GENERATED_DIR = "generated-proxies"
        private const val MIN_TEMPLATE_SIZE = 10_000

        /**
         * File name for a generated APK.
         *
         * Includes the target package so several proxies can coexist on disk, and stays inside
         * the cache dir so the system can reclaim it — the APK is trivially regenerable, unlike
         * the data it exists to rescue.
         */
        fun fileNameFor(packageName: String): String = "proxy-$packageName.apk"
    }
}

data class GeneratedApk(
    val file: File,
    val packageName: String,
    val authority: String,
    val sizeBytes: Int,
    val sha256Hex: String,
    val manifestReplacements: List<Pair<String, String>>,
)
