package dev.understudy.bridge

/**
 * Why a bridge operation failed.
 *
 * Modelled as a sealed type rather than throwing platform exceptions because the failure modes
 * here are *expected* and each needs different UI: "proxy not installed" is a call to action,
 * "path rejected" is a bug report, and "protocol mismatch" means "regenerate and reinstall".
 * Collapsing them into `Exception` would lose exactly the distinction the user needs.
 */
sealed class BridgeError(message: String, cause: Throwable? = null) : Exception(message, cause) {

    /**
     * No provider answers at that authority.
     *
     * **This does not mean "not installed", and saying so was actively misleading.** From API 30
     * the platform filters package visibility, and the filter covers `ContentResolver` authority
     * resolution, so an *installed, running* proxy that the app is not allowed to see produces the
     * identical `IllegalArgumentException: Unknown authority`. CI run #29 is the evidence: five
     * tests failing with this message while `adb shell content query` against the same URI returned
     * rows in the same log. See `research/06-milestone5-bridge-permission-ownership.md`.
     *
     * The two causes have different remedies, so the message names both. The second one is a real
     * upgrade path rather than a hypothetical: a proxy generated by a build from before the
     * discovery receiver existed does not advertise `BridgeContract.DISCOVERY_ACTION`, so a
     * current build cannot see it no matter how correctly it was installed. Regenerating it is the
     * fix, and that is what the user is told.
     */
    class ProxyUnreachable(val authority: String, cause: Throwable) : BridgeError(
        "No proxy responds at authority '$authority'. Either it is not installed in this user " +
            "profile, or it is installed but not visible to Understudy — Android 11+ filters " +
            "package visibility, and a proxy generated by an older build does not advertise the " +
            "discovery action this one looks for. Regenerate and reinstall the proxy.",
        cause,
    )

    /**
     * The provider exists and was reachable, but refused us.
     *
     * Almost always `ProxyFileBridge.enforceCaller()`: the calling uid's signing certificate does
     * not match the SHA-256 of the certificate belonging to the install that generated the proxy.
     * That happens when Understudy has been **replaced by a differently-signed build** — which
     * invalidates every proxy the old one made, deliberately, because those proxies must stop
     * trusting the new app — or when the proxy came from another install or another device.
     *
     * It is *not* the `signature`-level `BRIDGE` permission, and this message used to say that it
     * was. `:app` defines that permission, so `:app` always holds it, whatever signed the proxy;
     * blaming the proxy's key sent support looking at the one certificate that could not be the
     * problem. If the permission really were missing the platform would refuse the call before any
     * provider code ran, which surfaces here identically — so the message covers that too, but
     * leads with the cause that can actually occur.
     */
    class PermissionDenied(val authority: String, cause: Throwable) : BridgeError(
        "The proxy at '$authority' refused access: this is not the Understudy install that " +
            "generated it. Replacing Understudy with a differently-signed build invalidates every " +
            "proxy the previous one made. Regenerate and reinstall the proxy.",
        cause,
    )

    /** The proxy answered but reports a protocol version we do not speak. */
    class ProtocolMismatch(val theirs: Int, val ours: Int) : BridgeError(
        "Proxy speaks protocol v$theirs but this app speaks v$ours. Regenerate and reinstall it.",
    )

    /** The proxy is installed but its package name is not the one we asked for. */
    class WrongIdentity(val expected: String, val actual: String) : BridgeError(
        "The proxy at '$actual' is not impersonating '$expected'.",
    )

    /** Our own path validation rejected the request before it left the process. */
    class InvalidPath(val path: String, reason: String) : BridgeError(
        "Refusing path '$path': $reason",
    )

    /** The proxy validated the path and still refused it. */
    class RejectedByProxy(val path: String, reason: String) : BridgeError(
        "Proxy rejected '$path': $reason",
    )

    /** Entry does not exist. Distinct from I/O failure so "refresh" is not shown as an error. */
    class NotFound(val path: String) : BridgeError("No such entry: $path")

    class Io(val path: String, cause: Throwable) : BridgeError(
        "I/O failed on '$path': ${cause.message}", cause,
    )

    /** Storage not mounted, or the root directory could not be resolved by the proxy. */
    class RootUnavailable(val root: String) : BridgeError(
        "The proxy could not resolve root '$root'. Is external storage mounted?",
    )

    /**
     * The proxy returned `ok=false` with a reason we do not otherwise classify, or the platform
     * threw something we do not recognise.
     *
     * [cause] is optional and was missing entirely until a test asked for it. It matters on the
     * unrecognised-exception path: [fromLookup] stringifies the throwable into [reason], which
     * preserves the message but throws away the stack trace, and the stack trace is the only thing
     * that says *where* it came from. Every other [BridgeError] subtype that wraps a platform
     * exception keeps it; this one should not be the exception to that.
     */
    class OperationFailed(
        val operation: String,
        val reason: String,
        cause: Throwable? = null,
    ) : BridgeError("$operation failed: $reason", cause)

    companion object {
        /**
         * Maps the two exceptions the platform throws when a provider cannot be reached.
         *
         * `IllegalArgumentException` ("Unknown authority") means the app could not *resolve* the
         * provider — either nothing is installed there, or it is installed and not visible. The
         * platform does not distinguish them and neither can we; see [ProxyUnreachable].
         *
         * `SecurityException` means resolution succeeded but the call was refused: either the
         * platform's `android:permission` gate, or `enforceCaller()`'s generator-certificate
         * check. Both mean "regenerate and reinstall", which is why one error type is enough.
         *
         * The distinction between the two is worth preserving even though the remedy converges:
         * unreachable is a discovery problem, denied is a trust problem, and a future build with
         * an actual remedy for one of them will need to tell them apart.
         */
        fun fromLookup(authority: String, t: Throwable): BridgeError = when {
            // A path refusal arrives as a SecurityException too, and means the opposite of a caller
            // refusal: this one is per-file and the transfer should continue. See
            // BridgeClient.classifySecurity and BridgeContract.PATH_REJECTION_MARKER.
            t is SecurityException &&
                (t.message ?: "").startsWith(BridgeContract.PATH_REJECTION_MARKER) ->
                RejectedByProxy(
                    authority,
                    (t.message ?: "").removePrefix(BridgeContract.PATH_REJECTION_MARKER),
                )
            t is SecurityException -> PermissionDenied(authority, t)
            t is IllegalArgumentException -> ProxyUnreachable(authority, t)
            else -> OperationFailed(
                "contacting $authority",
                "${t.javaClass.simpleName}: ${t.message}",
                t,
            )
        }
    }
}
